export default () => ({
  radialPanelLoading: true,
  radialRefresh: false,
  chemicals: [],
  neighborChemicals: [],
  radialPanelError: false,
  fingerprints: [],
  validFpArr: [],
  filterBy: [],
  showMultipleFpPopover: false,
  multipleFpSelections: [],
  maxHybridFp: null,
  lastWorkingRadialParams: {
    fp: 'chm_mrgn',
    k0: 10,
    sel_by: 'tox_txrf',
    chem_id: '',
    summarise: 'tox_txrf',
    sumrs_by: 'tox_fp',
    s0: 0.1,
    neg0: 1,
    pos0: 1,
    engine: 'genrapred',
  },
  neighborhoodGraphData: {},
  neighborhoodLoading: false,
  graphFps: [],
  modifiedGraphFps: [],
  graphNeighbors: 3,
  graphFpColors: {},
  graphTypes: [],
  selectedGraphType: '',
  neighborhoodGraphFilterBy: '',
  physchemPlotUrl: '',
  customNeighborhood: [],
})
