export default () => ({
  readAcrossChemicals: [],
  readAcrossGrid: [],
  runReadAcrossGrid: [],
  graReadAcrossColumns: [],
  rraReadAcrossColumns: [],
  readAcrossLoading: true,
  readAcrossError: false,
  readAcrossStepError: false,
  runReadAcrossLoading: false,
  runReadAcrossError: false,
  genra: ['GenRA'],
  min: [...Array(11).keys()].slice(1),
  downloadValue: null,
  similarityWidth: false,
  filter: '',
  showPagination: true,
  readAcrossFilterApplied: false,
  readAcrossFilteredAssays: [],
  graSortOptions: [],
  graLatestSortOption: {
    order: '', option: '',
  },
  rraSortOptions: [],
  disableDownload: false,
  predEngines: [],
})
