name: Container-security-scan

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ dev, staging ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}


jobs:
  container-scan:

    runs-on: th878
    environment: ${{ github.head_ref || github.ref_name }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Create .env file for build  
      - name: Creating .env file
        run: echo "$ENV_TEXT" > .env
        env:
          ENV_TEXT: ${{vars.ENV_TEXT}}
          
      - name: Docker build
        run: docker build -f docker/Dockerfile -t genra-ui-security-${{ github.head_ref || github.ref_name }} .

      - name: Create Output Folder
        run: mkdir output   
          
      - name: Run security scan on the container
        uses: aquasecurity/trivy-action@0.12.0
        id:   scan
        with:
          image-ref: 'genra-ui-security-${{ github.head_ref || github.ref_name }}'
          format: template
          template: "@/contrib/html.tpl"
          output: ./output/genra-ui-report.html
          severity: 'CRITICAL,HIGH'
          
          
      - name: Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v4
        with: 
          name: container-scan-report
          path: output
          
      - name: remove previous trivy report
        run: rm -rf /data/watchtower/genra/container-results/genra_ui/genra-ui-report.html
   
      - name: download artifacts to the computer    
        uses: actions/download-artifact@v4
        with:
          name: container-scan-report
          path: /data/watchtower/genra/container-results/genra_ui 
