name: Trufflehog-Scan
on:
  push:
    branches: [ "dev" ]
  pull_request:
  
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Scan with TruffleHog OSS
      id: trufflehog-scan
      uses: trufflesecurity/trufflehog@main
      continue-on-error: true
      with:
        base: "${{ github.event.repository.default_branch }}"
        #head: HEAD
        extra_args: --debug --only-verified --json
        path: ./
        
    - name: Fail workflow due to scan failing
      if: steps.trufflehog-scan.outcome == 'failure'
      run: exit 1    
      
    - name: Scan Results Status
      if: steps.trufflehog-scan.outcome == 'success'
      run: echo "NO SECRETS FOUND!"
        
   
  
